### ISSUE TITLE
error

### ISSUE THREAD

**Issue by huiwudiyi** [guillaumejaume/edGNN#1]
Traceback (most recent call last):
  File "preprocess", line 23, in <module>
    module = importlib.import_module(MODULE.format(dataset))
  File "/opt/conda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'core'

**Comment by guillaumejaume** [comment]
It might be that you didn't add edGNN in your `PYTHONPATH`. Try adding it by doing:

 `export PYTHONPATH="YOUR-PATH/edGNN"` or directly adding it to your bashrc.

**Comment by huiwudiyi** [comment]
Thanks！！！
