### ISSUE TITLE
FileNotFoundError of run_model

### ISSUE THREAD

**Issue by duanyanan** [guillaumejaume/edGNN#4]
```~/dyn/edGNN$ run_model --dataset mutag  --config_fpath ./core/models/config_files/config_edGNN_graph_class.json  --data_path ./graphs/mutag/

*** Set default saving/loading path to: checkpoint_06c91595-25a3-4eef-b650-1857be688607.pt
Traceback (most recent call last):
  File "/home/anyua/anaconda3/envs/edgnn/bin/run_model", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/anyua/dyn/edGNN/bin/run_model", line 100, in <module>
    main(args)
  File "/home/anyua/dyn/edGNN/bin/run_model", line 41, in main
    data = module.load_dglrgcn(args.data_path)
  File "/home/anyua/dyn/edGNN/core/data/dglrgcn.py", line 83, in load_dglrgcn
    data[k] = torch.load(complete_path(folder, k))
  File "/home/anyua/anaconda3/envs/edgnn/lib/python3.6/site-packages/torch/serialization.py", line 365, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: './graphs/mutag/train_mask'```

I have already run preprocess as 
```preprocess dortmund --dataset mutag --out_folder ./graphs/mutag/```
how can I fix it?

**Comment by duanyanan** [comment]
I find that train_mask file is generated by dglrgcn.py, so I first run preprocess as `preprocess dglrgcn --dataset mutag --out_folder ./graphs/mutag/`.
Then I run run_model as `run_model --dataset mutag  --config_fpath ./core/models/config_files/config_edGNN_graph_class.json  --data_path ./graphs/mutag/`.

Now it is training.
